# This file was generated by GoReleaser. DO NOT EDIT.
cask "slk" do
  version "0.24.1"

  on_macos do
    on_arm do
      sha256 "baf5d0492620a117c99bf8f43b72a4eca9f4b19320f884e50db3d1c57fd24540"
      url "https://github.com/gammons/slk/releases/download/v#{version}/slk_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "cdf8d2996b083f0cbb12d9f1752b6fdf3cad26231cac30b59cd7eb37e0e0fa7f"
      url "https://github.com/gammons/slk/releases/download/v#{version}/slk_#{version}_darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "afab685df755cf929d67ad65633088d8e3bae8d15d66c4eac6932e4eef21bb25"
      url "https://github.com/gammons/slk/releases/download/v#{version}/slk_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "440846b12a422c6222ecf976b63ce2d7b46c38ef19a795ce7374ef169cbe57f9"
      url "https://github.com/gammons/slk/releases/download/v#{version}/slk_#{version}_linux_x86_64.tar.gz"
    end
  end

  name "slk"
  desc "A blazingly fast, keyboard-driven Slack TUI"
  homepage "https://github.com/gammons/slk"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slk"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/slk"]
    end
  end

  # No zap stanza required
end
