# This file was generated by GoReleaser. DO NOT EDIT.
cask "slk" do
  version "0.16.0"

  on_macos do
    on_intel do
      sha256 "d8c1cd4834d3b9cbd4d3f43e45d6979d2025a4b5533b36bf0ed0f2064c5bd55e"
      url "https://github.com/gammons/slk/releases/download/v#{version}/slk_#{version}_darwin_x86_64.tar.gz",
        verified: "github.com/gammons/slk"
    end
    on_arm do
      sha256 "0d5eba2140ced0a69281a3643f732a80dcef7d1b3fea9b74075214d76d21dcbe"
      url "https://github.com/gammons/slk/releases/download/v#{version}/slk_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/gammons/slk"
    end
  end

  on_linux do
    on_intel do
      sha256 "8c304ee1b73847f9e524211a87db9a1e59ca841d359a2b71547d81e593f93ea3"
      url "https://github.com/gammons/slk/releases/download/v#{version}/slk_#{version}_linux_x86_64.tar.gz",
        verified: "github.com/gammons/slk"
    end
    on_arm do
      sha256 "d1f592f4f7f1e7fceaa05234ac75d2ea151ad791a540bcdce1b33c5f4877a416"
      url "https://github.com/gammons/slk/releases/download/v#{version}/slk_#{version}_linux_arm64.tar.gz",
        verified: "github.com/gammons/slk"
    end
  end

  name "slk"
  desc "A blazingly fast, keyboard-driven Slack TUI"
  homepage "https://github.com/gammons/slk"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slk"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/slk"]
    end
  end

  # No zap stanza required

end
