# This file was generated by GoReleaser. DO NOT EDIT.
cask "slk" do
  version "0.14.0"

  on_macos do
    on_intel do
      sha256 "95b9cfc53f0c6496be5779704e958a456964e982d6226ab723a8d6c73bb49d5f"
      url "https://github.com/gammons/slk/releases/download/v#{version}/slk_#{version}_darwin_x86_64.tar.gz",
        verified: "github.com/gammons/slk"
    end
    on_arm do
      sha256 "4c614c129281d79a963f4c57cd9e87dd40968f8ee5e342417853baed5351c1cf"
      url "https://github.com/gammons/slk/releases/download/v#{version}/slk_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/gammons/slk"
    end
  end

  on_linux do
    on_intel do
      sha256 "982fd82fd49af99b04f5b9c6b9cf01b3c04c426e137cfb946476ae83ccbdacbb"
      url "https://github.com/gammons/slk/releases/download/v#{version}/slk_#{version}_linux_x86_64.tar.gz",
        verified: "github.com/gammons/slk"
    end
    on_arm do
      sha256 "a0173d67273168d8035da43b265b05592b770eb84340ebfeec239e58c451f8a7"
      url "https://github.com/gammons/slk/releases/download/v#{version}/slk_#{version}_linux_arm64.tar.gz",
        verified: "github.com/gammons/slk"
    end
  end

  name "slk"
  desc "A blazingly fast, keyboard-driven Slack TUI"
  homepage "https://github.com/gammons/slk"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slk"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/slk"]
    end
  end

  # No zap stanza required

end
