# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slk < Formula
  desc "A blazingly fast, keyboard-driven Slack TUI"
  homepage "https://github.com/gammons/slk"
  version "0.8.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gammons/slk/releases/download/v0.8.7/slk_0.8.7_darwin_x86_64.tar.gz"
      sha256 "ce78fe6433a54b994fedadab048630fcfd79930b3bd72845a171c8f86a450fda"

      define_method(:install) do
        bin.install "slk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gammons/slk/releases/download/v0.8.7/slk_0.8.7_darwin_arm64.tar.gz"
      sha256 "3d41cb95bca8c32495393e5be1b217051b48afe3e9851868dfc98c94fa54975a"

      define_method(:install) do
        bin.install "slk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gammons/slk/releases/download/v0.8.7/slk_0.8.7_linux_x86_64.tar.gz"
      sha256 "b87b35646d3b51b298ee564c1aefa995be48507d13195332eb4e0c10f3722307"
      define_method(:install) do
        bin.install "slk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gammons/slk/releases/download/v0.8.7/slk_0.8.7_linux_arm64.tar.gz"
      sha256 "935f737fbc5fb90172b883744a5c6eded223a086d28c0337530516e7efd6114a"
      define_method(:install) do
        bin.install "slk"
      end
    end
  end

  def caveats
    <<~EOS
      First run: `slk login` to authenticate with your Slack workspace.
      Config lives in ~/.config/slk/.
    EOS
  end

  test do
    assert_match "slk", shell_output("#{bin}/slk --version")
  end
end
