# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slk < Formula
  desc "A blazingly fast, keyboard-driven Slack TUI"
  homepage "https://github.com/gammons/slk"
  version "0.8.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gammons/slk/releases/download/v0.8.4/slk_0.8.4_darwin_x86_64.tar.gz"
      sha256 "a833c535a51dbf0f8c4125b432b8e9b7ceca142248bf7f9d9276689c6c396daa"

      define_method(:install) do
        bin.install "slk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gammons/slk/releases/download/v0.8.4/slk_0.8.4_darwin_arm64.tar.gz"
      sha256 "2792c6bfc8e861b953b5197b8c682a4d4c0dc006aa72df27ccaf1663f1d17f3f"

      define_method(:install) do
        bin.install "slk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gammons/slk/releases/download/v0.8.4/slk_0.8.4_linux_x86_64.tar.gz"
      sha256 "f568e1c22e199a1a7f46da4754cb0d304b7bd2e5858c25b7e475930a55bfc870"
      define_method(:install) do
        bin.install "slk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gammons/slk/releases/download/v0.8.4/slk_0.8.4_linux_arm64.tar.gz"
      sha256 "31b090ed1d4f043a0cd9c60143c97bd82e2b705da602ae00ed9235758e83d1e2"
      define_method(:install) do
        bin.install "slk"
      end
    end
  end

  def caveats
    <<~EOS
      First run: `slk login` to authenticate with your Slack workspace.
      Config lives in ~/.config/slk/.
    EOS
  end

  test do
    assert_match "slk", shell_output("#{bin}/slk --version")
  end
end
